export const languages = {
  ".py": {
    language: "python",
    separators: [
      "\nclass ",
      "\ndef ",
      "\n\tdef ",
      "\nasync ",
      "\n\tasync ",
      "\n\n",
      "\n",
      " ",
      "",
    ],
  },
  ".ts": {
    language: "typescript",
    separators: [
      "\nclass ",
      "\ninterface ",
      "\nenum ",
      "\nfunction ",
      "\nnamespace ",
      "\nvar ",
      "\nlet ",
      "\nconst ",
      "\nasync function ",
      "\n\n",
      "\n",
      " ",
      "",
    ],
  },
  ".js": {
    language: "javascript",
    separators: [
      "\nfunction ",
      "\nclass ",
      "\nvar ",
      "\nlet ",
      "\nconst ",
      "\nasync function ",
      "\n\n",
      "\n",
      " ",
      "",
    ],
  },
  ".php": {
    language: "php",
    separators: [
      "\nclass ",
      "\ninterface ",
      "\ntrait ",
      "\nfunction ",
      "\npublic ",
      "\nprivate ",
      "\nprotected ",
      "\nnamespace ",
      "\nuse ",
      "\n\n",
      "\n",
      " ",
      "",
    ],
  },
  ".rb": {
    language: "ruby",
    separators: [
      "\nclass ",
      "\nmodule ",
      "\ndef ",
      "\nalias ",
      "\nbegin ",
      "\nrescue ",
      "\nensure ",
      "\nend ",
      "\n\n",
      "\n",
      " ",
      "",
    ],
  },
  ".rs": {
    language: "rust",
    separators: [
      "\nfn ",
      "\nmod ",
      "\nstruct ",
      "\nenum ",
      "\nimpl ",
      "\ntrait ",
      "\nunion ",
      "\n   pub fn ",
      "\n   fn ",
      "\npub ",
      "\n\n",
      "\n",
      " ",
      "",
      // Split along control flow statements
    ],
  },
  ".md": {
    language: "markdown",
    separators: [
      "\n#{1,3} ",
      "```\n",
      "\n***+\n",
      "\n---+\n",
      "\n___+\n",
      "\n\n",
      "\n\n",
      "\n",
      " ",
      "",
    ],
  },
};
